/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MockERC20 } from './MockERC20'

export { MockERC20__factory } from './factories/MockERC20__factory'
